plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-minimal

title: Data Science Work
tagline: Include projects from Springboard Bootcamp
author:
        name: Ting Sit
        email: sitkevin@gmail.com
        github: sittingman
        linkedin: 