plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - INDEX.md

theme: jekyll-theme-leap-day

production_url : https://github.com/sittingman/sittingman.github.io
BASE_PATH : https://github.com/sittingman/sittingman.github.io

markdown : kramdown